#!/usr/bin/env bash
# Interactive light-effect mapper.
#
# Steps through the cooler's light-effect bytes one at a time, at YOUR pace.
# For each byte it lights the cooler in one test colour (red by default), waits
# for you to look, then asks what you saw. When you're done it writes the
# results to led_mapping.md in this folder.
#
# Usage:
#   ./probe_light.sh                 # walk bytes 0..15
#   ./probe_light.sh 0 8             # walk just bytes 0..8
#   COLOR="0 255 0" ./probe_light.sh # use green as the test colour instead of red
#
# At each prompt:
#   1  off / no light
#   2  rainbow (many colours at once)
#   3  solid single colour (steady, not moving)
#   4  breathing single colour (fades in and out)
#   5  spinning / running / chasing colour
#   6  something else  (you'll type a short description)
#   r  re-show this byte (didn't catch it)
#   s  skip this byte
#   q  quit now and save what we have

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
STATUS_FILE="$HOME/.redmagic_probe_status.json"
CMD_FILE="$HOME/.redmagic_probe_command.json"
OUT="$DIR/led_mapping.md"

FROM="${1:-0}"
TO="${2:-15}"
read -r CR CG CB <<< "${COLOR:-255 0 0}"   # test colour, default red

if [[ ! -f "$STATUS_FILE" ]] || ! python3 -c \
    "import json,time; d=json.load(open('$STATUS_FILE')); assert d.get('connected') and time.time()-d.get('ts',0)<5" \
    2>/dev/null; then
    echo "No connected probe build found. Run ./build.sh --with-probes --run first."
    exit 1
fi

send() { printf '{"light_mode":%d,"light_rgb":[%d,%d,%d]}' "$1" "$CR" "$CG" "$CB" > "$CMD_FILE"; }

echo "Turning cooler ON (medium) so the LED lights…"
printf '{"cooling_mode":2,"fan_speed":70,"auto_mode":false}' > "$CMD_FILE"
sleep 2

echo ""
echo "Test colour is RGB($CR,$CG,$CB). We'll walk bytes $FROM..$TO."
echo "Look at the cooler after each step, then answer the prompt."
echo ""

# Collected results, one "byte|label|notes" per line.
declare -a RESULTS=()

label_for() {
    case "$1" in
        1) echo "off" ;;
        2) echo "rainbow" ;;
        3) echo "solid single colour" ;;
        4) echo "breathing single colour" ;;
        5) echo "spinning / running colour" ;;
        *) echo "other" ;;
    esac
}

byte="$FROM"
while [[ "$byte" -le "$TO" ]]; do
    send "$byte"
    sleep 1
    printf '\n── byte 0x%02X (%d) is now showing ─────────────────────────\n' "$byte" "$byte"
    echo "What do you see? [1 off · 2 rainbow · 3 solid · 4 breathing · 5 spinning · 6 other · r re-show · s skip · q quit]"
    read -r choice

    case "$choice" in
        r|R) continue ;;                       # re-show same byte
        s|S) byte=$((byte + 1)); continue ;;   # skip
        q|Q) break ;;
        1|2|3|4|5)
            RESULTS+=("$byte|$(label_for "$choice")|")
            ;;
        6)
            printf 'Describe what you saw: '
            read -r notes
            RESULTS+=("$byte|other|$notes")
            ;;
        *)
            echo "(didn't understand '$choice' — re-showing this byte)"
            continue
            ;;
    esac
    byte=$((byte + 1))
done

# ── Write the mapping file ───────────────────────────────────────────────────
{
    echo "# Cooler LED effect mapping"
    echo ""
    echo "Generated by probe_light.sh on $(date '+%Y-%m-%d %H:%M')."
    echo "Test colour: RGB($CR,$CG,$CB)."
    echo ""
    echo "| effect byte | what I saw | notes |"
    echo "|-------------|------------|-------|"
    for row in "${RESULTS[@]}"; do
        IFS='|' read -r b l n <<< "$row"
        printf '| %d (0x%02X) | %s | %s |\n' "$b" "$b" "$l" "$n"
    done
} > "$OUT"

echo ""
echo "Restoring colourful breath + auto cooling…"
printf '{"light_mode":2,"auto_mode":true}' > "$CMD_FILE"

echo ""
echo "Saved mapping to: $OUT"
echo "Check it over, then wire the useful bytes into LedEffect.DeviceEffect."
